version: 0.2

phases:
  install:
    commands:
      - echo "Installing boto3 and sagemaker"
      - pip3 install boto3
      - pip3 install tensorflow
      - pip3 install sagemaker

  build:
    commands:
      - echo "Running test.py"
      - python3 ml-test/iris-dnn/test.py "ml-backend/$CONFIGURATION_FILE"
